/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import datos.Cliente;
import datos.Empleado;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.Lista;
import main.ProgramaPrincipal;

/**
 *
 * @author Nertrox
 */
public class FrBorrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form JFrameBuscarCliente
     */
    Empleado activo;
    public FrBorrarCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTable1.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 24));
        this.activo = activo;
        llenarTabla();
    }

    private String formatear(String num) {
         String s1 = num.substring(0, 4) + "-";
        s1 += num.substring(4);
        return s1;
    }

    private String desformatear(String num) {
        String[] formateado = num.split("-");
        String desformateado = "";
        for (int i = 0; i < formateado.length; i++) {
            desformateado += formateado[i];
        }
        return desformateado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JRadioNombre = new javax.swing.JRadioButton();
        jRadioTel = new javax.swing.JRadioButton();
        jRadioApellido = new javax.swing.JRadioButton();
        jTextFieldBusqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JButtonSeleccionar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(149, 165, 166));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 107, 70), 10, true));

        jPanel2.setBackground(new java.awt.Color(189, 195, 199));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar Cliente Por"));

        JRadioNombre.setBackground(new java.awt.Color(189, 195, 199));
        buttonGroup.add(JRadioNombre);
        JRadioNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JRadioNombre.setSelected(true);
        JRadioNombre.setText("Nombre");

        jRadioTel.setBackground(new java.awt.Color(189, 195, 199));
        buttonGroup.add(jRadioTel);
        jRadioTel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRadioTel.setText("Teléfono");

        jRadioApellido.setBackground(new java.awt.Color(189, 195, 199));
        buttonGroup.add(jRadioApellido);
        jRadioApellido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRadioApellido.setText("Apellido");

        jTextFieldBusqueda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBusquedaActionPerformed(evt);
            }
        });
        jTextFieldBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBusquedaKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JRadioNombre)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioApellido)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioTel)
                                .addGap(46, 46, 46)
                                .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(JRadioNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioTel)
                            .addComponent(jTextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        JButtonSeleccionar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JButtonSeleccionar.setText("Borrar");
        JButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSeleccionarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonCancelar.setText("Salir");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(JButtonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(261, 261, 261))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarTabla() {

        jTable1.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 24));
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int cant = ProgramaPrincipal.datos.getClientes().largo();

        if (cant > 0) {
            String tel;
            for (int i = 0; i < cant; i++) {
                Cliente c = (Cliente) ProgramaPrincipal.datos.getClientes().obtener(i);
                tel = formatear(c.getTelefono());
                model.addRow(new Object[]{c.getNombre() , c.getApellido(), tel});
            }
        }

    }
    
    private void buscar(){
        boolean tel = jRadioTel.isSelected();
        boolean nombre = JRadioNombre.isSelected();
        boolean apellido = jRadioApellido.isSelected();

        ArrayList<Cliente> encontrados = new ArrayList<>();

        if (tel) {
            encontrados = buscarPorTelefono();
        }

        if (nombre) {
            encontrados = buscarPorNombre();
        }

        if (apellido) {
            encontrados = buscarPorApellido();
        }

        llenarTabla(encontrados);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        buscar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void JButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSeleccionarActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        Cliente cliente = ProgramaPrincipal.datos.obtenerCliente(desformatear(String.valueOf(model.getValueAt(row, 2))));
        int opcion = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar este cliente?","Eliminar",JOptionPane.YES_NO_OPTION);
        
        if (opcion == JOptionPane.YES_OPTION){
            ProgramaPrincipal.datos.getClientes().eliminar(cliente);
            ProgramaPrincipal.datos.guardarClientes(ProgramaPrincipal.pathC);
            model.removeRow(jTable1.getSelectedRow());
        }
        
    }//GEN-LAST:event_JButtonSeleccionarActionPerformed

    private void jTextFieldBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBusquedaActionPerformed

    private void jTextFieldBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscar();
        }
    }//GEN-LAST:event_jTextFieldBusquedaKeyPressed

    private ArrayList<Cliente> buscarPorTelefono() {
        Lista clientes = (Lista) ProgramaPrincipal.datos.getClientes();
        ArrayList<Cliente> encontrados = new ArrayList<>();
        int largo = clientes.largo();
        String busqueda = jTextFieldBusqueda.getText();
        Cliente c = null;

        for (int i = 0; i < largo; i++) {
            c = (Cliente) clientes.obtener(i);
            if (c.getTelefono().contains(busqueda)) {
                encontrados.add(c);
            }
        }
        return encontrados;
    }

    private ArrayList<Cliente> buscarPorNombre() {
        Lista clientes = (Lista) ProgramaPrincipal.datos.getClientes();
        ArrayList<Cliente> encontrados = new ArrayList<>();
        int largo = clientes.largo();
        String busqueda = jTextFieldBusqueda.getText().toLowerCase();
        Cliente c = null;
        for (int i = 0; i < largo; i++) {
            c = (Cliente) clientes.obtener(i);
            if (c.getNombre().toLowerCase().contains(busqueda)) {
                encontrados.add(c);
            }
        }
        return encontrados;
    }

    private ArrayList<Cliente> buscarPorApellido() {
        Lista clientes = (Lista) ProgramaPrincipal.datos.getClientes();
        ArrayList<Cliente> encontrados = new ArrayList<>();
        int largo = clientes.largo();
        String busqueda = jTextFieldBusqueda.getText().toLowerCase();
        Cliente c = null;
        for (int i = 0; i < largo; i++) {
            c = (Cliente) clientes.obtener(i);
            if (c.getApellido().toLowerCase().contains(busqueda)) {
                encontrados.add(c);
            }
        }
        return encontrados;
    }

    private void llenarTabla(ArrayList<Cliente> encontrados) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int cant = model.getRowCount();
        model.setRowCount(0);
        
        String tel;
        for (Cliente c : encontrados) {
            tel = formatear(c.getTelefono());
            model.addRow(new Object[]{c.getNombre(), c.getApellido(),tel});
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonSeleccionar;
    private javax.swing.JRadioButton JRadioNombre;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioApellido;
    private javax.swing.JRadioButton jRadioTel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBusqueda;
    // End of variables declaration//GEN-END:variables
}
