/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import datos.Caja;
import datos.Categoria;
import main.ProgramaPrincipal;
import datos.Pizza;
import datos.Topping;
import java.awt.Font;
import negocio.Lista;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nertrox
 */
public class FrEditarPizza extends javax.swing.JFrame {

    boolean copiar = false;
    /**
     * Creates new form FrEditarPizza
     */
    private final String pizza;
    private final Pizza backUp;

    public FrEditarPizza(String pizza) {
        initComponents();
        setLocationRelativeTo(null);
        this.pizza = pizza;
        Pizza original = ProgramaPrincipal.datos.obtenerPizza(pizza);
        backUp = original.crearCopias();
        llenarTablaToppings();
        jTextFieldNombre.setText(original.getNombre());
        jTextFieldDesc.setText(original.getDescripcion());

        String precio = "₡" + String.format("%,d", original.getPrecio());
        jTextFielPrecio.setText(precio);
        llenarCombo();
    }

    public FrEditarPizza(String pizza, boolean copiar) {
        initComponents();
        setLocationRelativeTo(null);
        this.pizza = pizza;
        Pizza original = ProgramaPrincipal.datos.obtenerPizza(pizza);
        backUp = original.crearCopias();
        llenarTablaToppings();
        jTextFieldNombre.setText(original.getNombre());
        jTextFieldDesc.setText(original.getDescripcion());
        String precio = "₡" + String.format("%,d", original.getPrecio());
        jTextFielPrecio.setText(precio);
        this.copiar = copiar;
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldDesc = new javax.swing.JTextField();
        jTextFielPrecio = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableToppings = new javax.swing.JTable();
        jComboBoxCaja = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(149, 165, 166));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 107, 70), 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Descripcion");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Precio");

        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jTextFieldDesc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescActionPerformed(evt);
            }
        });

        jTextFielPrecio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFielPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielPrecioActionPerformed(evt);
            }
        });

        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEliminar.setText("Eliminar Topping");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Toppings");

        Guardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Guardar.setText("Guardar Cambios");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        JTableToppings.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JTableToppings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad Necesaria (gr)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableToppings.setRowHeight(40);
        JTableToppings.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(JTableToppings);
        if (JTableToppings.getColumnModel().getColumnCount() > 0) {
            JTableToppings.getColumnModel().getColumn(0).setResizable(false);
            JTableToppings.getColumnModel().getColumn(1).setResizable(false);
        }

        jComboBoxCaja.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Caja");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFielPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jComboBoxCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFielPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llenarCombo() {
        Lista cajas = ProgramaPrincipal.datos.getCajas();
        Caja c;
        for (int i = 0; i < cajas.cantidad(); i++) {
            c = (Caja) cajas.obtener(i);
            jComboBoxCaja.addItem(c.getNombre());
        }

        for (int i = 0; i < jComboBoxCaja.getItemCount(); i++) {
            String item = String.valueOf(jComboBoxCaja.getItemAt(i));
            if (item.equals(backUp.getCaja())) {
                jComboBoxCaja.setSelectedIndex(i);
                return;
            }
        }
    }

    private void formatearNumeros() {

        String value = "";
        String numero;
        for (int i = 0; i < JTableToppings.getRowCount(); i++) {
            numero = String.valueOf(JTableToppings.getValueAt(i, 1));
            value += String.format("%,d", Integer.valueOf(numero));
            JTableToppings.setValueAt(value, i, 1);
            value = "";
        }
    }

    private void llenarTablaToppings() {
        JTableToppings.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 24));
        DefaultTableModel model = (DefaultTableModel) JTableToppings.getModel();
        model.setRowCount(0);
        Lista toppings = ProgramaPrincipal.datos.obtenerPizza(pizza).getToppings();
        if (toppings.largo() != 0) {
            for (int i = 0; i < toppings.largo(); i++) {
                model.addRow(new Object[]{((Topping) toppings.obtener(i)).getNombre(), ((Topping) toppings.obtener(i)).getCantidadNecesaria()});
            }
        }

        formatearNumeros();
    }
    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescActionPerformed

    private void jTextFielPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielPrecioActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        DefaultTableModel model = (DefaultTableModel) JTableToppings.getModel();

        int filas = JTableToppings.getRowCount();

        if (filas > 1) {
            int opcion = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar este topping?", "Eliminar Topping", JOptionPane.YES_OPTION, JOptionPane.WARNING_MESSAGE);
            if (opcion == JOptionPane.YES_OPTION) {
                String topping = String.valueOf(model.getValueAt(JTableToppings.getSelectedRow(), 0));
                ProgramaPrincipal.datos.obtenerPizza(pizza).removerTopping(topping);
                model.setRowCount(0);
                llenarTablaToppings();
            }
        } else {
            JOptionPane.showMessageDialog(this, "No puede dejar la pizza sin toppings!");
        }

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        ProgramaPrincipal.datos.getPizzas().modificar(new Pizza(jTextFieldNombre.getText()), backUp);
        JOptionPane.showMessageDialog(this, "No se guardaron los cambios");
        FrModificarProductos fr = new FrModificarProductos();
        fr.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed

        String nombre = jTextFieldNombre.getText();
        String descripcion = jTextFieldDesc.getText();
        Pizza producto = ProgramaPrincipal.datos.obtenerPizza(pizza);
        boolean bandera = false;
        if (descripcion.equals("") || nombre.equals("")) {
            JOptionPane.showMessageDialog(this, "Ha dejado algun campo en blanco!");
        } else {
            try {
                guardarCambiosTabla();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ha ingresado una cantidad incorrecta!");
                bandera = true;

            }
            if (!bandera) {
                try {
                    String p = jTextFielPrecio.getText();
                    p = quitarColon(p);
                    int precio = Integer.parseInt(p);
                    producto.setNombre(nombre);
                    producto.setDescripcion(descripcion);
                    producto.setPrecio(precio);
                    producto.setCaja(String.valueOf(jComboBoxCaja.getSelectedItem()));
                    JOptionPane.showMessageDialog(this, "Guardado de forma correcta!");
                    ProgramaPrincipal.datos.getPizzas().ordenar();
                    ProgramaPrincipal.datos.guardarPizzas(ProgramaPrincipal.pathP);
                    FrModificarProductos fr = new FrModificarProductos();
                    fr.setVisible(true);
                    this.dispose();

                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Ha ingresado un precio incorecto!");
                }
            }
        }

    }//GEN-LAST:event_GuardarActionPerformed

    private String quitarColon(String valor) {
        String desformateado;

        if (valor.charAt(0) == '₡') {
            desformateado = valor.substring(1);
            desformateado = desformatear(desformateado);
        } else {
            desformateado = desformatear(valor);
        }

        return desformateado;
    }

    private String desformatear(String value) {

        String formateado[] = value.split(",");
        String desformateado = "";
        for (int i = 0; i < formateado.length; i++) {
            desformateado += formateado[i];
        }

        return desformateado;
    }

    private void guardarCambiosTabla() throws NumberFormatException {
        int filas = JTableToppings.getRowCount();
        String top;
        int cantidad;
        Pizza producto = ProgramaPrincipal.datos.obtenerPizza(pizza);

        for (int i = 0; i < filas; i++) {
            top = String.valueOf(JTableToppings.getValueAt(i, 0));
            String c = String.valueOf(JTableToppings.getValueAt(i, 1));
            c = desformatear(c);
            cantidad = Integer.parseInt(c);
            producto.modificarTopping(top, cantidad);
            //topping = (Topping) Main.datos.getToppings().consultar(new Topping(top));
            //(Pizza) Main.datos.getPizzas().consultar(new Pizza(pizza))).agregarTopping(topping, cantidad);

        }
    }

    private void guardarCopia() {
        String nombre = jTextFieldNombre.getText();
        String descripcion = jTextFieldDesc.getText();
        String p = jTextFielPrecio.getText();
        p = quitarColon(p);
        Pizza producto = new Pizza(nombre);
        System.out.println(producto);
        int precio = Integer.parseInt(p);
        producto.setDescripcion(descripcion);
        producto.setPrecio(precio);
        producto.setCategoria(Categoria.PIZZA);
        producto.setCaja(String.valueOf(jComboBoxCaja.getSelectedItem()));

        int filas = JTableToppings.getRowCount();
        String top;
        int cantidad;
        Topping topping;
        for (int i = 0; i < filas; i++) {
            top = String.valueOf(JTableToppings.getValueAt(i, 0));
            topping = ProgramaPrincipal.datos.obtenerTopping(top);
            String c = String.valueOf(JTableToppings.getValueAt(i, 1));
            c = desformatear(c);
            cantidad = Integer.parseInt(c);
            producto.agregarTopping(topping, cantidad);
            //topping = (Topping) Main.datos.getToppings().consultar(new Topping(top));
            //(Pizza) Main.datos.getPizzas().consultar(new Pizza(pizza))).agregarTopping(topping, cantidad);

        }

        ProgramaPrincipal.datos.agregarProducto(producto);
        ProgramaPrincipal.datos.getPizzas().ordenar();
        ProgramaPrincipal.datos.guardarPizzas(ProgramaPrincipal.pathP);

    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JTable JTableToppings;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JComboBox<String> jComboBoxCaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFielPrecio;
    private javax.swing.JTextField jTextFieldDesc;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
