/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import datos.Bebida;
import datos.Categoria;
import datos.Cliente;
import datos.Combo;
import datos.Empleado;
import datos.Factura;
import datos.Orden;
import datos.Pizza;
import datos.Producto;
import hilos.HiloPrecio;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import main.ProgramaPrincipal;
import negocio.Lista;

/**
 *
 * @author Nertrox
 */
public class FrOrdenar extends javax.swing.JFrame {

    /**
     * Creates new form FrOrdenar
     */
    private Cliente cliente;
    private Empleado empleado;
    private ArrayList<Categoria> tipoProd;
    private Orden ordenCliente;
    private boolean express;
    private final Date fecha;
    private HiloPrecio hilo;

    public FrOrdenar() {
        initComponents();
        fecha = new Date();
        setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    public FrOrdenar(Cliente cliente, Empleado activo) {
        this.cliente = cliente;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.empleado = activo;
        initComponents();
        fecha = new Date();
        llenarInfo();
        setLocationRelativeTo(null);
        tipoProd = new ArrayList<>();
        inicarHilo();
        express = false;

    }

    private static String formatear(String num) {
        String s1 = num.substring(0, 4) + "-";
        s1 += num.substring(4);
        return s1;
    }

    private void inicarHilo() {
        hilo = new HiloPrecio(jLabelTotal, jLabelExpress, jTableOrden, jLabelSubTotal);
        hilo.start();
    }

    private void llenarInfo() {
        jTableOrden.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 24));
        jTextFieldCliente.setText(cliente.getNombre() + " " + cliente.getApellido());
        jTextFieldOrden.setText(String.valueOf(ProgramaPrincipal.datos.obtenerNumeroOrden()));
        jTextAreaDir.setText(cliente.getDireccion());
        jTextFieldTel.setText(formatear(cliente.getTelefono()));
        jTextFieldEmpleado.setText(empleado.getLogin());
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
        String formato = format.format(fecha);
        jTextFieldFecha.setText(formato);

    }

    public void agregarProducto(String nombre, String cant, String precio, Categoria categoria) {
        DefaultTableModel modelo = (DefaultTableModel) jTableOrden.getModel();
        modelo.addRow(new Object[]{nombre, cant, precio});
        tipoProd.add(categoria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDir = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldOrden = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmpleado = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOrden = new javax.swing.JTable();
        jButtonEliminar = new javax.swing.JButton();
        jButtonAumentar = new javax.swing.JButton();
        jButtonDisminuir = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonProductos = new javax.swing.JButton();
        jButtonProcesar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jToggleButtonExpress = new javax.swing.JToggleButton();
        jToggleButtonLlevar = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelSubTotal = new javax.swing.JLabel();
        jLabelExpress = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jRadioButtonEfectivo = new javax.swing.JRadioButton();
        jRadioButtonTarjeta = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(149, 165, 166));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 107, 70), 10, true));

        jPanel2.setBackground(new java.awt.Color(189, 195, 199));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cliente:");

        jTextFieldCliente.setEditable(false);
        jTextFieldCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Telefono:");

        jTextFieldTel.setEditable(false);
        jTextFieldTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Direccion:");

        jTextAreaDir.setColumns(20);
        jTextAreaDir.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextAreaDir.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDir);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("# Orden:");

        jTextFieldOrden.setEditable(false);
        jTextFieldOrden.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Fecha:");

        jTextFieldFecha.setEditable(false);
        jTextFieldFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Creada por:");

        jTextFieldEmpleado.setEditable(false);
        jTextFieldEmpleado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(189, 195, 199));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTableOrden.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTableOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOrden.setRowHeight(40);
        jTableOrden.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableOrden);
        if (jTableOrden.getColumnModel().getColumnCount() > 0) {
            jTableOrden.getColumnModel().getColumn(0).setResizable(false);
            jTableOrden.getColumnModel().getColumn(0).setPreferredWidth(400);
            jTableOrden.getColumnModel().getColumn(1).setResizable(false);
            jTableOrden.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTableOrden.getColumnModel().getColumn(2).setResizable(false);
            jTableOrden.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonAumentar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAumentar.setText("Aumentar");
        jButtonAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAumentarActionPerformed(evt);
            }
        });

        jButtonDisminuir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDisminuir.setText("Disminuir");
        jButtonDisminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisminuirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAumentar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDisminuir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAumentar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDisminuir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(189, 195, 199));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar Orden");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonProductos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonProductos.setText("Ver Productos");
        jButtonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductosActionPerformed(evt);
            }
        });

        jButtonProcesar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonProcesar.setText("Procesar Orden");
        jButtonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jButtonProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonProcesar)
                .addContainerGap(374, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonProcesar, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addComponent(jButtonProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(jToggleButtonExpress);
        jToggleButtonExpress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButtonExpress.setText("Express");
        jToggleButtonExpress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonExpressActionPerformed(evt);
            }
        });

        buttonGroup1.add(jToggleButtonLlevar);
        jToggleButtonLlevar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButtonLlevar.setText("Para LLevar");
        jToggleButtonLlevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonLlevarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonLlevar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jToggleButtonExpress, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButtonExpress, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonLlevar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(368, 368, 368))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(189, 195, 199));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Detalles de orden", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Sub Total:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Express: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Total:");

        jLabelSubTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSubTotal.setText("0");

        jLabelExpress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelExpress.setText("0");

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTotal.setText("0");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("₡");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("₡");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("₡");

        jRadioButtonEfectivo.setBackground(new java.awt.Color(189, 195, 199));
        buttonGroup2.add(jRadioButtonEfectivo);
        jRadioButtonEfectivo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRadioButtonEfectivo.setSelected(true);
        jRadioButtonEfectivo.setText("Pago en efectivo");

        jRadioButtonTarjeta.setBackground(new java.awt.Color(189, 195, 199));
        buttonGroup2.add(jRadioButtonTarjeta);
        jRadioButtonTarjeta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRadioButtonTarjeta.setText("Pago con tarjeta");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelExpress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonEfectivo)
                            .addComponent(jRadioButtonTarjeta))
                        .addGap(145, 145, 145))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSubTotal)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelExpress)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jRadioButtonEfectivo)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonTarjeta)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductosActionPerformed
        JFrameInventarioOrden fr = new JFrameInventarioOrden(this);
        fr.setVisible(true);
    }//GEN-LAST:event_jButtonProductosActionPerformed

    private String desformatear(String value) {

        String formateado[] = value.split(",");
        String desformateado = "";
        for (int i = 0; i < formateado.length; i++) {
            desformateado += formateado[i];
        }

        return desformateado;
    }

    private String quitarColon(String valor) {
        String desformateado;

        if (valor.charAt(0) == '₡') {
            desformateado = valor.substring(1);
            desformateado = desformatear(desformateado);
        } else {
            desformateado = desformatear(valor);
        }

        return desformateado;
    }
    private void jButtonAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAumentarActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableOrden.getModel();
        int cantidad = Integer.parseInt(String.valueOf(model.getValueAt(jTableOrden.getSelectedRow(), 1)));
        int precio = Integer.parseInt(quitarColon(String.valueOf(model.getValueAt(jTableOrden.getSelectedRow(), 2))));

        precio = precio / cantidad;
        cantidad++;
        model.setValueAt(cantidad, jTableOrden.getSelectedRow(), 1);

        String tot = "₡" + String.format("%,d", Integer.valueOf(String.valueOf(cantidad * precio)));
        model.setValueAt(tot, jTableOrden.getSelectedRow(), 2);
    }//GEN-LAST:event_jButtonAumentarActionPerformed

    private void jButtonDisminuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisminuirActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableOrden.getModel();
        int cantidad = Integer.parseInt(String.valueOf(model.getValueAt(jTableOrden.getSelectedRow(), 1)));
        int precio = Integer.parseInt(quitarColon(String.valueOf(model.getValueAt(jTableOrden.getSelectedRow(), 2))));

        precio = precio / cantidad;
        if (cantidad > 1) {
            cantidad--;
            model.setValueAt(cantidad, jTableOrden.getSelectedRow(), 1);
            String tot = "₡" + String.format("%,d", Integer.valueOf(String.valueOf(cantidad * precio)));
            model.setValueAt(tot, jTableOrden.getSelectedRow(), 2);
        }
    }//GEN-LAST:event_jButtonDisminuirActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableOrden.getModel();
        tipoProd.remove(jTableOrden.getSelectedRow());
        model.removeRow(jTableOrden.getSelectedRow());
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcesarActionPerformed

        Map backUpToppigns = ProgramaPrincipal.datos.backUpToppings();
        Map backUpBebidas = ProgramaPrincipal.datos.backUpBebidas();

        int numeroOrden = ProgramaPrincipal.datos.obtenerNumeroOrden();
        express = jToggleButtonExpress.isSelected();
        Orden orden = new Orden(cliente, numeroOrden, fecha, express, empleado);
        DefaultTableModel model = (DefaultTableModel) jTableOrden.getModel();
        int cantidadFilas = jTableOrden.getRowCount();
        int total = Integer.valueOf(desformatear(jLabelTotal.getText()));
        //System.out.println(jLabelTotal.getText());
        if (cantidadFilas > 0) {
            String nombre;
            //int precio;
            int cantidad; //cant de prod ordenado
            Categoria c;
            for (int i = 0; i < cantidadFilas; i++) {
                cantidad = Integer.parseInt(String.valueOf(model.getValueAt(i, 1)));
                nombre = String.valueOf(model.getValueAt(i, 0));
                //precio = Integer.parseInt(quitarColon(String.valueOf(model.getValueAt(i, 2))));
                c = tipoProd.get(i);
                Producto producto = crearProd(c, nombre);
               // System.out.println(producto);
                producto.setCantidadOrdenada(cantidad);
                orden.getProductos().agregar(producto);
                //total += precio;
            }

            try {
                int express = Integer.parseInt(desformatear(jLabelExpress.getText()));
                //total += express;
                orden.setPrecioExpress(express);
                orden.setTotal(total);
            } catch (NumberFormatException e) {

            }

            if (validarOrden(orden, backUpToppigns, backUpBebidas)) {
                ordenCliente = orden;
                if (jRadioButtonEfectivo.isSelected()) {
                    ordenCliente.setTarjeta(false);
                    procesarPago(total, backUpToppigns, backUpBebidas);
                } else {
                    ordenCliente.setTarjeta(true);
                    completarOrden();
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "No hay ningun producto para procesar la orden!");
        }


    }//GEN-LAST:event_jButtonProcesarActionPerformed

    public void procesarPago(int total, Map backUpToppigns, Map backUpBebidas) {
        FrProcesarPago fr = new FrProcesarPago(total, this, backUpToppigns, backUpBebidas);
        fr.setVisible(true);
    }

    public void completarOrden() {
        System.out.println("Total de la orden: " + ordenCliente.getTotal());
        cliente.aumentarOrdenes(1);
        cliente.aumentarDineroGastado(ordenCliente.getTotal());
        cliente.setDireccion(jTextAreaDir.getText());
        ProgramaPrincipal.datos.actualizarCantidadesTotales(ordenCliente);
        ProgramaPrincipal.datos.agregarOrden(ordenCliente);
        ProgramaPrincipal.datos.actualizarCantCajas(ordenCliente);
        ProgramaPrincipal.datos.guardarOtros(ProgramaPrincipal.pathProd);
        ProgramaPrincipal.datos.guardarClientes(ProgramaPrincipal.pathC);
        ProgramaPrincipal.datos.guardarPizzas(ProgramaPrincipal.pathP);
        ProgramaPrincipal.datos.guardarBebidas(ProgramaPrincipal.pathB);
        ProgramaPrincipal.datos.guardarToppings(ProgramaPrincipal.pathT);
        ProgramaPrincipal.datos.guardarCajas(ProgramaPrincipal.pathCajas);
        ProgramaPrincipal.datos.guardarOrdenes(ProgramaPrincipal.pathO);
        ProgramaPrincipal.datos.guardarCombos(ProgramaPrincipal.pathCombos);

        Factura factura = new Factura();
        factura.generarFactura(ordenCliente, ProgramaPrincipal.config.getImpresora());
        hilo.parar();
        this.dispose();
    }

    private boolean validarOrden(Orden orden, Map backUpToppigns, Map backUpBebidas) {
        Lista productos = orden.getProductos();
        Producto producto;
        int cantidad = productos.cantidad();
        boolean ordenValida = true;
        ArrayList<String> noValidos = new ArrayList<>();

        for (int i = 0; i < cantidad; i++) {
            producto = (Producto) productos.obtener(i);

            switch (producto.getCategoria()) {
                case BEBIDA: {
                    int disponibles = ProgramaPrincipal.datos.obtenerBebida(producto.getNombre()).getDisponibles();
                    int ordenadas = producto.getCantidadOrdenada();
                    if ((disponibles - ordenadas) < 0) {

                        if (!ProgramaPrincipal.config.isProhibirVenta()) {
                            Bebida b = (Bebida) ProgramaPrincipal.datos.obtenerBebida(producto.getNombre());
                            b.reducirDisponibles(ordenadas);
                        }
                        noValidos.add(producto.getNombre());
                        ordenValida = false;
                    } else {
                        Bebida b = (Bebida) ProgramaPrincipal.datos.obtenerBebida(producto.getNombre());
                        b.reducirDisponibles(ordenadas);
                    }

                    break;
                }
                case PIZZA: {
                    Pizza pizza = ProgramaPrincipal.datos.obtenerPizza(producto.getNombre());
                    if (!pizza.validarPizza(producto.getCantidadOrdenada())) {
                        noValidos.add(producto.getNombre());
                        ordenValida = false;
                    }
                    break;

                }

                case COMBO: {
                    Combo combo = ProgramaPrincipal.datos.obtenerCombo(producto.getNombre());
                    Lista productosCombo = combo.getProductos();
                    Producto prodCombo;
                    for (int j = 0; j < productosCombo.cantidad(); j++) {
                        prodCombo = (Producto) productosCombo.obtener(j);
                        if (prodCombo.getCategoria() == Categoria.PIZZA) {
                            Pizza pizza = ProgramaPrincipal.datos.obtenerPizza(prodCombo.getNombre());
                            if (!pizza.validarPizza(prodCombo.getCantidadEnCombo())) {
                                noValidos.add(prodCombo.getNombre());
                                ordenValida = false;
                            }
                        }

                        if (prodCombo.getCategoria() == Categoria.BEBIDA) {
                            int disponibles = ProgramaPrincipal.datos.obtenerBebida(prodCombo.getNombre()).getDisponibles();
                            int ordenadas = prodCombo.getCantidadEnCombo();
                            if ((disponibles - ordenadas) < 0) {

                                if (!ProgramaPrincipal.config.isProhibirVenta()) {
                                    Bebida b = (Bebida) ProgramaPrincipal.datos.obtenerBebida(prodCombo.getNombre());
                                    b.reducirDisponibles(ordenadas);
                                }
                                noValidos.add(prodCombo.getNombre());
                                ordenValida = false;
                            } else {
                                Bebida b = (Bebida) ProgramaPrincipal.datos.obtenerBebida(prodCombo.getNombre());
                                b.reducirDisponibles(ordenadas);
                            }
                        }
                    }
                }
            }
        }

        if (!ordenValida) {
            String mensaje = "No hay suficientes de los siguientes productos para completar la orden: \n";

            for (String nombre : noValidos) {
                mensaje += nombre + " \n";
            }
            mensaje += " \n Si entre los productos hay una pizza, quiere decir que faltan toppings para completar esa pizza!\n";

            if (!ProgramaPrincipal.config.isProhibirVenta()) {
                mensaje += "\nDesea continuar de todas formas?";
                int continuar = JOptionPane.showConfirmDialog(this, mensaje, "Alerta", JOptionPane.YES_NO_OPTION);

                if (continuar == JOptionPane.NO_OPTION) {
                    restaurarProds(backUpToppigns, backUpBebidas);
                } else {
                    ordenValida = true;
                }
            } else {
                JOptionPane.showMessageDialog(this, mensaje);
                restaurarProds(backUpToppigns, backUpBebidas);
            }

        }

        return ordenValida;
    }

    public void restaurarProds(Map backUpToppigns, Map backUpBebidas) {
        ProgramaPrincipal.datos.restaurarBebidas(backUpBebidas);
        ProgramaPrincipal.datos.restaurarToppings(backUpToppigns);
    }

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        hilo.parar();
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jToggleButtonExpressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonExpressActionPerformed
        String precio = JOptionPane.showInputDialog(this, "Ingrese el precio del express");

        try {
            int p = Integer.parseInt(desformatear(precio));
            precio = String.format("%,d", p);
            jLabelExpress.setText(precio);
        } catch (NumberFormatException e) {

        }

    }//GEN-LAST:event_jToggleButtonExpressActionPerformed

    private void jToggleButtonLlevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLlevarActionPerformed
        jLabelExpress.setText("0");
    }//GEN-LAST:event_jToggleButtonLlevarActionPerformed

    private void jTextFieldEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpleadoActionPerformed

    private Producto crearProd(Categoria c, String nombre) {

        switch (c) {
            case BEBIDA: {
                Producto b = ProgramaPrincipal.datos.obtenerBebida(nombre).crearCopia();
                return b;
            }
            case PIZZA: {
                Producto p = ProgramaPrincipal.datos.obtenerPizza(nombre).crearCopia();
                return p;
            }

            case CAJA: {
                Producto caja = ProgramaPrincipal.datos.obtenerCaja(nombre).crearCopia();
                return caja;
            }
            case OTRO: {
                Producto o = ProgramaPrincipal.datos.obtenerProducto(nombre).crearCopia();
                return o;
            }

            case COMBO: {
                Producto combo = ProgramaPrincipal.datos.obtenerCombo(nombre).crearCopia();
               // System.out.println(combo);
                return combo;
            }
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrOrdenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrOrdenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrOrdenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrOrdenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrOrdenar().setVisible(true);
            }
        });
    }

    public JTable getjTableOrden() {
        return jTableOrden;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonAumentar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDisminuir;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonProcesar;
    private javax.swing.JButton jButtonProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelExpress;
    private javax.swing.JLabel jLabelSubTotal;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButtonEfectivo;
    private javax.swing.JRadioButton jRadioButtonTarjeta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableOrden;
    private javax.swing.JTextArea jTextAreaDir;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldEmpleado;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldOrden;
    private javax.swing.JTextField jTextFieldTel;
    private javax.swing.JToggleButton jToggleButtonExpress;
    private javax.swing.JToggleButton jToggleButtonLlevar;
    // End of variables declaration//GEN-END:variables
}
