/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import datos.Cliente;
import datos.ClockIn;
import datos.Empleado;
import hilos.HiloRevisarInventario;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import main.ProgramaPrincipal;
import static main.ProgramaPrincipal.datos;

/**
 *
 * @author Nertrox
 */
public class FrPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private Empleado activo;
    private ClockIn registro;
    private hilos.HiloRevisarInventario hilo;
    public FrPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        registro = new ClockIn();
        hilo = new HiloRevisarInventario();
        revisarInventario();
        

    }
    
    public void revisarInventario(){
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonLogin = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        JButtonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFiedNumero = new javax.swing.JTextField();
        JButtonBuscar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAgregar = new javax.swing.JMenuItem();
        jMenuItemEditar = new javax.swing.JMenuItem();
        jMenuItemAumentar = new javax.swing.JMenuItem();
        jMenuItemMostrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemVerEmpleado = new javax.swing.JMenuItem();
        jMenuAgregarMaestro = new javax.swing.JMenuItem();
        jMenuItemAddEmpleado = new javax.swing.JMenuItem();
        jMenuItemAdministrar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemVerOrdenes = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuResetear = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(jPanel1.getSize());

        jPanel1.setBackground(new java.awt.Color(149, 165, 166));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 107, 70), 10, true));

        jPanel2.setBackground(new java.awt.Color(189, 195, 199));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonLogin.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButtonLogin.setText("Log In");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jButtonLogout.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButtonLogout.setText("Log Out");
        jButtonLogout.setEnabled(false);
        jButtonLogout.setPreferredSize(new java.awt.Dimension(135, 53));
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(189, 195, 199));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JButtonBuscar.setText("Buscar Cliente");
        JButtonBuscar.setEnabled(false);
        JButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Numero del cliente");

        jTextFiedNumero.setEditable(false);
        jTextFiedNumero.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextFiedNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFiedNumeroActionPerformed(evt);
            }
        });
        jTextFiedNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFiedNumeroKeyPressed(evt);
            }
        });

        JButtonBuscar1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        JButtonBuscar1.setText("Buscar Factura");
        JButtonBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                            .addComponent(jTextFiedNumero))
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JButtonBuscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(JButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFiedNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(JButtonBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jPanel4.setBackground(new java.awt.Color(189, 195, 199));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Salir del Programa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(22, 107, 70));
        jLabel2.setText("Pronto");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(22, 107, 70));
        jLabel3.setText("Pizza");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(93, 93, 93)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(189, 195, 199));

        jMenu1.setBackground(new java.awt.Color(255, 51, 51));
        jMenu1.setText("Inventario");

        jMenuItemAgregar.setText("Agregar Productos");
        jMenuItemAgregar.setEnabled(false);
        jMenuItemAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAgregar);

        jMenuItemEditar.setText("Editar Productos");
        jMenuItemEditar.setEnabled(false);
        jMenuItemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemEditar);

        jMenuItemAumentar.setText("Aumentar Inventario");
        jMenuItemAumentar.setEnabled(false);
        jMenuItemAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAumentarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAumentar);

        jMenuItemMostrar.setText("Mostrar Inventario");
        jMenuItemMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMostrarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemMostrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clientes");

        jMenuItem4.setText("Agregar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem17.setText("Eliminar");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem17);

        jMenuItem9.setText("Ver");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Empleados");

        jMenuItemVerEmpleado.setText("Ver");
        jMenuItemVerEmpleado.setEnabled(false);
        jMenuItemVerEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerEmpleadoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemVerEmpleado);

        jMenuAgregarMaestro.setText("Agregar Maestro");
        jMenuAgregarMaestro.setEnabled(false);
        jMenuAgregarMaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgregarMaestroActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuAgregarMaestro);

        jMenuItemAddEmpleado.setText("Agregar ");
        jMenuItemAddEmpleado.setEnabled(false);
        jMenuItemAddEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddEmpleadoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAddEmpleado);

        jMenuItemAdministrar.setText("Administrar ");
        jMenuItemAdministrar.setEnabled(false);
        jMenuItemAdministrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdministrarActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAdministrar);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Reportes");

        jMenu7.setText("Clientes");

        jMenuItem10.setText("Frecuentes");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenuItem11.setText("Ingresos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem11);

        jMenu3.add(jMenu7);

        jMenu8.setText("Productos");

        jMenuItem12.setText("Ventas");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem12);

        jMenu3.add(jMenu8);

        jMenu9.setText("Empleados");

        jMenuItem14.setText("Entrada/Salida");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem14);

        jMenu3.add(jMenu9);

        jMenuItem16.setText("Ventas");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem16);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Ventas");

        jMenuItemVerOrdenes.setText("Ver Todas");
        jMenuItemVerOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerOrdenesActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemVerOrdenes);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Buscar Por Fecha");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem7.setText("Buscar Por Cliente");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("Buscar Por Empleado");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem13.setText("Buscar Por Numero");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Configuracion");

        jMenuItem1.setText("Alertas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuItem15.setText("Impresora");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem15);

        jMenuItem3.setText("Crear respaldo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuItem5.setText("Recuperar respaldo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuResetear.setText("Resetear Inventario");
        jMenuResetear.setEnabled(false);
        jMenuResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuResetearActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuResetear);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setActivo(Empleado activo) {
        this.activo = activo;
    }

    public Empleado getActivo() {
        return activo;
    }

    public void clockIn(Date date) {
        registro.setEntrada(date);
    }

    public void clockOut(Date date) {
        registro.setSalida(date);
    }

    public void validarPermisos() {
        if (activo.isAdministrador() || activo.isUsuarioMaestro()) {
            jMenuItemAddEmpleado.setEnabled(true);
            jMenuItemVerEmpleado.setEnabled(true);
            jMenuItemAgregar.setEnabled(true);
            jMenuItemAumentar.setEnabled(true);
            jMenuItemEditar.setEnabled(true);

        } else {
            jMenuItemAddEmpleado.setEnabled(false);
            jMenuItemVerEmpleado.setEnabled(false);
            jMenuItemAgregar.setEnabled(false);
            jMenuItemAumentar.setEnabled(false);
            jMenuItemEditar.setEnabled(false);
            jMenuResetear.setEnabled(false);

        }
        
        if (activo.isUsuarioMaestro()){
            jMenuAgregarMaestro.setEnabled(true);
            jMenuItemAdministrar.setEnabled(true);
            jMenuResetear.setEnabled(true);
        }
        if (!activo.isUsuarioMaestro()){
            jMenuAgregarMaestro.setEnabled(false);
            jMenuItemAdministrar.setEnabled(false);
            jMenuResetear.setEnabled(false);
        }
        JButtonBuscar.setEnabled(true);
        jTextFiedNumero.setEditable(true);
    }

    public void deshabilitarButonLogin() {
        jButtonLogin.setEnabled(false);
    }

    
    private void jMenuItemAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarActionPerformed
        FrAgregarProducto producto = new FrAgregarProducto();
        producto.setVisible(true);

    }//GEN-LAST:event_jMenuItemAgregarActionPerformed

    private void jMenuItemAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAumentarActionPerformed
        JFrameAumentarProd frToppings = new JFrameAumentarProd();
        frToppings.setVisible(true);
    }//GEN-LAST:event_jMenuItemAumentarActionPerformed

    private void jMenuItemMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMostrarActionPerformed
        JFrameInventario inventario = new JFrameInventario();
        inventario.setVisible(true);
    }//GEN-LAST:event_jMenuItemMostrarActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FrAgregarClientes cliente = new FrAgregarClientes();
        cliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarActionPerformed
        FrModificarProductos frMod = new FrModificarProductos();
        frMod.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditarActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        FrMostrarClientes fr = new FrMostrarClientes();
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void JButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonBuscarActionPerformed
        JFrameBuscarCliente fr = new JFrameBuscarCliente(activo);
        fr.setVisible(true);
    }//GEN-LAST:event_JButtonBuscarActionPerformed

    private void jTextFiedNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFiedNumeroActionPerformed

    }//GEN-LAST:event_jTextFiedNumeroActionPerformed

    private void jTextFiedNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFiedNumeroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscar();
        }
    }//GEN-LAST:event_jTextFiedNumeroKeyPressed

    public void habilitarLogout(){
        jButtonLogout.setEnabled(rootPaneCheckingEnabled);
    }
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        FrIniciarSesion fr = new FrIniciarSesion(this);
        fr.setVisible(true);
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jMenuItemVerEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerEmpleadoActionPerformed
        FrMostrarEmpleados fr = new FrMostrarEmpleados(activo);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerEmpleadoActionPerformed

    private void jMenuItemAddEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddEmpleadoActionPerformed
        FrAgregarEmpleado fr = new FrAgregarEmpleado(0);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItemAddEmpleadoActionPerformed

    private void jMenuItemVerOrdenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerOrdenesActionPerformed
        FrVerOrdenes fr = new FrVerOrdenes();
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerOrdenesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrAjustes fr = new FrAjustes();
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed

        registro.setSalida(new Date());
        activo.marcarRegistro(registro);
        activo = null;
        ProgramaPrincipal.datos.guardarEmpleados(ProgramaPrincipal.pathE);

        registro = new ClockIn();
        jMenuItemAddEmpleado.setEnabled(false);
        jMenuItemVerEmpleado.setEnabled(false);
        jMenuItemAgregar.setEnabled(false);
        jMenuItemAumentar.setEnabled(false);
        jMenuItemEditar.setEnabled(false);
        JButtonBuscar.setEnabled(false);
        jTextFiedNumero.setEditable(false);
        jButtonLogin.setEnabled(true);
        jButtonLogout.setEnabled(false);
        jMenuAgregarMaestro.setEnabled(false);
        jMenuItemAdministrar.setEnabled(false);
        jMenuResetear.setEnabled(false);


    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        FrReporteClientes fr = new FrReporteClientes(0);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        FrReporteClientes fr = new FrReporteClientes(1);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        FrReporteProductos fr = new FrReporteProductos();
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        FrReportEmpleados fr = new FrReportEmpleados();
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFileChooser archivo = new JFileChooser();
        archivo.setDialogTitle("Carpeta en donde guardar");
        archivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int retorno = archivo.showSaveDialog(this);

        if (retorno == JFileChooser.APPROVE_OPTION) {
            String root = archivo.getSelectedFile().toString();
            root += "\\Respaldo";


            String pathCli = root + "\\" + "Clientes";
            String pathEmp = root + "\\" + "Empleados";
            String pathOrd = root + "\\" + "Ordenes";
            String pathPiz = root + "\\" + "Pizzas";
            String pathBeb = root + "\\" + "Bebidas";
            String pathOtr = root + "\\" + "Productos";
            String pathTop = root + "\\" + "Toppigns";
            String pathCaj = root + "\\" + "Cajas";

            datos.guardarClientes(pathCli);
            datos.guardarEmpleados(pathEmp);
            datos.guardarOrdenes(pathOrd);
            datos.guardarPizzas(pathPiz);
            datos.guardarBebidas(pathBeb);
            datos.guardarOtros(pathOtr);
            datos.guardarToppings(pathTop);
            datos.guardarCajas(pathCaj);

            JOptionPane.showMessageDialog(this, "Respaldo Guardaddo");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JFileChooser archivo = new JFileChooser();
        archivo.setDialogTitle("Carpeta de donde cargar");
        archivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int retorno = archivo.showOpenDialog(this);
        if (retorno == JFileChooser.APPROVE_OPTION) {
            String root = archivo.getSelectedFile().toString();
            
            String pathCli = root + "\\" + "Clientes";
            String pathEmp = root + "\\" + "Empleados";
            String pathOrd = root + "\\" + "Ordenes";
            String pathPiz = root + "\\" + "Pizzas";
            String pathBeb = root + "\\" + "Bebidas";
            String pathOtr = root + "\\" + "Productos";
            String pathTop = root + "\\" + "Toppigns";
            String pathCaj = root + "\\" + "Cajas";

            datos.cargarPizzas(pathPiz);
            datos.cargarBebidas(pathBeb);
            datos.cargarToppings(pathTop);
            datos.cargarOtros(pathOtr);
            datos.cargarClientes(pathCli);
            datos.cargarEmpleados(pathEmp);
            datos.cargarOdenes(pathOrd);
            datos.cargarCajas(pathCaj);
            
            File directory = new File("datos");
            if (!directory.exists()) {
                directory.mkdir();
            }
            datos.guardarBebidas(ProgramaPrincipal.pathB);
            datos.guardarCajas(ProgramaPrincipal.pathCajas);
            datos.guardarClientes(ProgramaPrincipal.pathC);
            datos.guardarEmpleados(ProgramaPrincipal.pathE);
            datos.guardarOrdenes(ProgramaPrincipal.pathO);
            datos.guardarOtros(ProgramaPrincipal.pathProd);
            datos.guardarPizzas(ProgramaPrincipal.pathP);
            datos.guardarToppings(ProgramaPrincipal.pathT);

        }


    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (activo != null) {
            JOptionPane.showMessageDialog(this, "Debe hacer \"Log Out\" antes de cerrar el programa!");
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        frOrdenesFecha fr = new frOrdenesFecha(true);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FrBuscarOrdenes fr = new FrBuscarOrdenes(0);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FrBuscarOrdenes fr = new FrBuscarOrdenes(1);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
       FrBuscarOrdenes fr = new FrBuscarOrdenes(2);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        FrConfigImpresora fr = new FrConfigImpresora();
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuAgregarMaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgregarMaestroActionPerformed
        FrAgregarEmpleadoMaestro fr = new FrAgregarEmpleadoMaestro(0);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuAgregarMaestroActionPerformed

    private void jMenuItemAdministrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdministrarActionPerformed
        FrAdministrarEmpleados fr = new FrAdministrarEmpleados(activo);
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItemAdministrarActionPerformed

    private void JButtonBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonBuscar1ActionPerformed
        frOrdenesFecha fr = new frOrdenesFecha(true);
        fr.setVisible(true);
    }//GEN-LAST:event_JButtonBuscar1ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        frOrdenesFecha fr = new frOrdenesFecha();
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        FrBorrarCliente fr  = new FrBorrarCliente();
        fr.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuResetearActionPerformed
        ProgramaPrincipal.datos.resetearIngredientesCajas();
        ProgramaPrincipal.datos.resetearVentas();
    }//GEN-LAST:event_jMenuResetearActionPerformed

    private String desformatear(String num) {
        String[] formateado = num.split("-");
        String desformateado = "";
        for (int i = 0; i < formateado.length; i++) {
            desformateado += formateado[i];
        }
        return desformateado;
    }
    private void buscar() {
        String num = desformatear(jTextFiedNumero.getText());
        Cliente c = ProgramaPrincipal.datos.obtenerCliente(num);

        if (c == null) {
            int opcion = JOptionPane.showConfirmDialog(this, "No se encontro un cliente con ese numero.\n" + "Desea agregar un cliente nuevo?", "Cliente Nuevo", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                FrAgregarClientes fr = new FrAgregarClientes(true, activo,num);
                fr.setVisible(true);
            }
        } else {
            FrOrdenar fr = new FrOrdenar(c, activo);
            fr.setVisible(true);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonBuscar;
    private javax.swing.JButton JButtonBuscar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuItem jMenuAgregarMaestro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemAddEmpleado;
    private javax.swing.JMenuItem jMenuItemAdministrar;
    private javax.swing.JMenuItem jMenuItemAgregar;
    private javax.swing.JMenuItem jMenuItemAumentar;
    private javax.swing.JMenuItem jMenuItemEditar;
    private javax.swing.JMenuItem jMenuItemMostrar;
    private javax.swing.JMenuItem jMenuItemVerEmpleado;
    private javax.swing.JMenuItem jMenuItemVerOrdenes;
    private javax.swing.JMenuItem jMenuResetear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFiedNumero;
    // End of variables declaration//GEN-END:variables
}
